# Regularly restore the prediction models from cache to prevent cache eviction
name: "Labeler: Cache Retention"

# For more information about GitHub's action cache limits and eviction policy, see:
# https://docs.github.com/actions/writing-workflows/choosing-what-your-workflow-does/caching-dependencies-to-speed-up-workflows#usage-limits-and-eviction-policy

on:
  schedule:
    - cron: "36 4 * * *" # 4:36 every day (arbitrary time daily)

  workflow_dispatch:
    inputs:
      cache_key:
        description: "The cache key suffix to use for restoring the model from cache. Defaults to 'ACTIVE'."
        required: true
        default: "ACTIVE"

env:
  CACHE_KEY: ${{ inputs.cache_key || 'ACTIVE' }}

jobs:
  restore-cache:
    # Do not automatically run the workflow on forks outside the 'jeffhandley' org
    if: ${{ github.event_name == 'workflow_dispatch' || github.repository_owner == 'jeffhandley' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        type: ["issues", "pulls"]
    steps:
      - uses: jeffhandley/issue-labeler/restore@65943219795a6ac3abb8509c3ee706249490e62f # v2.0.0
        with:
          type: ${{ matrix.type }}
          cache_key: ${{ env.CACHE_KEY }}
          fail-on-cache-miss: true
